version: '3.4'

services:
  shopping.api:
    container_name: shopping.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings:ConnectionString=mongodb://shopping-db:27017
    depends_on:
      - shopping-db
    ports:
      - "8000:80"

  shopping.client:
    container_name: shopping.client
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BaseUrl=http://shopping.api
    depends_on:
      - shopping.api
      - shopping-db
    ports:
      - "8001:80"

  shopping-db:
    container_name: shopping-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db

